
services:
  payment-processor:
    image: payment-processor:latest
    container_name: payment-processor-default
    hostname: payment-processor-default
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - postgres-socket:/var/run/postgresql
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=/var/run/postgresql;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    depends_on:
      - payment-processor-db-1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "1.5"
          memory: "100MB"
    
  payment-processor-db-1:
    image: postgres:17-alpine
    container_name: payment-processor-default-db
    hostname: payment-processor-default-db
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-socket:/var/run/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - 54321:5432
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "1.5"
          memory: "250MB"

volumes:
  postgres-socket:
